In [10]:
import numpy as np
from scipy.io import loadmat
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [11]:
x = loadmat('../Data/M1-DeepSquat.mat')
correct = x['Train_Data']
T1 = correct.shape[1]
incorrect = x['Test_Data']
T2 = incorrect.shape[1]

In [12]:
Train_Data = []
Test_Data = []
for i in range(T1):
    Train_Data.append(correct[0,i])
for i in range(T2):
    Test_Data.append(incorrect[0,i])
Train_Data = np.dstack(Train_Data)
Train_Data = np.rollaxis(Train_Data,-1)
Test_Data = np.dstack(Test_Data)
Test_Data = np.rollaxis(Test_Data,-1)


In [13]:
samples = Train_Data.shape[0]
timesteps = Train_Data.shape[1]
features = Train_Data.shape[2]
Train_Data = np.reshape(Train_Data,(samples*timesteps,features))
Test_Data = np.reshape(Test_Data,(samples*timesteps,features))

In [14]:
Train_Data = StandardScaler().fit_transform(Train_Data)
print(Train_Data.shape)

(21600, 117)


In [15]:
#PCA
pca = PCA(n_components=4)
pca.fit(Train_Data)
Train_Data_Reduced = pca.transform(Train_Data)
print(pca.n_components_)
print(Train_Data_Reduced.shape)
print(Train_Data_Reduced)
Test_Data_Reduced = pca.transform(Test_Data)
print(pca.n_components_)
print(Test_Data_Reduced.shape)
print(Test_Data_Reduced)

4
(21600, 4)
[[11.09071883  5.01149452 -2.65187126 -2.71927212]
 [11.02539393  4.99412491 -2.68627639 -2.71465139]
 [10.95714298  4.9804887  -2.71852829 -2.70244616]
 ...
 [ 9.96499929 -3.62125592 -4.39632691  0.04471683]
 [ 9.97921274 -3.59844566 -4.34516664 -0.03057417]
 [ 9.98940306 -3.57669937 -4.29304715 -0.10204239]]
4
(21600, 4)
[[ 0.92182311  0.02087207  0.08971613 -0.16039581]
 [ 0.91990876  0.02095868  0.09057687 -0.16061109]
 [ 0.91794083  0.0210621   0.09143229 -0.16094129]
 ...
 [ 1.37661763  0.13050396 -0.47609934  0.42225764]
 [ 1.39423625  0.13370517 -0.48203623  0.43395256]
 [ 1.41104729  0.13680842 -0.48749777  0.44519904]]


In [16]:
Train_Data_Reduced = np.reshape(Train_Data_Reduced,(samples,timesteps,pca.n_components_))
Test_Data_Reduced = np.reshape(Test_Data_Reduced,(samples,timesteps,pca.n_components_))

In [17]:
csv_correct = Train_Data_Reduced.reshape(samples,timesteps*pca.n_components_)
np.savetxt('../Data/PCA_reduced_correct.csv', csv_correct ,delimiter=',')
csv_incorrect = Test_Data_Reduced.reshape(samples,timesteps*pca.n_components_)
np.savetxt('../Data/PCA_reduced_incorrect.csv', csv_incorrect ,delimiter=',')